// Generated by scripts/build.mjs — do not edit directly.
window.__ModuleLoader__.load({
  id: "dsh-delete-chat",
  factory: function (require) {
    var module = { exports: {} };
    var exports = module.exports;
    (function (module, exports, require) {
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/client.js
var client_exports = {};
__export(client_exports, {
  apply: () => apply,
  inject: () => inject
});
module.exports = __toCommonJS(client_exports);
var import_react = __toESM(require("react"), 1);
var inject = ["remote"];
var PACKAGE = "dsh-delete-chat";
var NAMESPACE = "delChat";
var SECTION_ID = "del-chat";
var CSS_TAG = "dsh-delete-chat/client.css";
var e = import_react.default.createElement;
function codecOf(parse) {
  return { parse };
}
var anyCodec = codecOf((value) => value);
var codec = (typeName) => ({
  mode: "strict",
  typeSymbol: `${PACKAGE}#${typeName}`,
  schema: anyCodec
});
var REMOTE_CONTRIBUTION = {
  package: PACKAGE,
  descriptors: [
    {
      id: `${PACKAGE}#${NAMESPACE}/list`,
      service: NAMESPACE,
      namespace: NAMESPACE,
      method: "list",
      invocation: { kind: "direct" },
      parameters: [{ name: "request", wire: "request", source: "json", codec: codec("ListRequest") }],
      result: codec("ListResult")
    },
    {
      id: `${PACKAGE}#${NAMESPACE}/archive`,
      service: NAMESPACE,
      namespace: NAMESPACE,
      method: "archive",
      invocation: { kind: "direct" },
      parameters: [{ name: "request", wire: "request", source: "json", codec: codec("SessionRequest") }],
      result: codec("ArchivedIdsResult")
    },
    {
      id: `${PACKAGE}#${NAMESPACE}/unarchive`,
      service: NAMESPACE,
      namespace: NAMESPACE,
      method: "unarchive",
      invocation: { kind: "direct" },
      parameters: [{ name: "request", wire: "request", source: "json", codec: codec("SessionRequest") }],
      result: codec("ArchivedIdsResult")
    },
    {
      id: `${PACKAGE}#${NAMESPACE}/inspectDelete`,
      service: NAMESPACE,
      namespace: NAMESPACE,
      method: "inspectDelete",
      invocation: { kind: "direct" },
      parameters: [{ name: "request", wire: "request", source: "json", codec: codec("SessionRequest") }],
      result: codec("InspectDeleteResult")
    },
    {
      id: `${PACKAGE}#${NAMESPACE}/deleteSession`,
      service: NAMESPACE,
      namespace: NAMESPACE,
      method: "deleteSession",
      invocation: { kind: "direct" },
      parameters: [{ name: "request", wire: "request", source: "json", codec: codec("SessionRequest") }],
      result: codec("DeleteResult")
    }
  ]
};
var CSS = [
  ".dc-root{display:flex;flex-direction:column;gap:16px;font-size:13px}",
  ".dc-head{display:flex;align-items:center;justify-content:space-between}",
  ".dc-head-title{font-weight:600;font-size:15px}",
  ".dc-section{border:1px solid var(--dsw-alias-border-l1,rgba(128,128,128,.35));border-radius:10px;padding:10px 12px}",
  ".dc-section-title{font-weight:600;margin-bottom:8px;opacity:.85}",
  ".dc-row{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:8px 0;border-top:1px solid var(--dsw-alias-border-l1,rgba(128,128,128,.18))}",
  ".dc-row:first-of-type{border-top:0}",
  ".dc-row-main{min-width:0;flex:1}",
  ".dc-row-title{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}",
  ".dc-row-sub{opacity:.6;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;margin-top:2px}",
  ".dc-empty{opacity:.5;padding:4px 0}",
  ".dc-live{color:var(--dsw-alias-state-info-primary,#4aa3e0);font-size:11px;margin-top:2px}",
  ".dc-warn{color:var(--dsw-alias-state-warn-primary,#e0a060);font-size:11px;margin-top:4px;word-break:break-all}",
  ".dc-actions{display:flex;align-items:center;gap:8px;flex-shrink:0}",
  ".dc-btn{font:inherit;font-size:12px;color:inherit;background:var(--dsw-alias-button-elevated-fill,transparent);border:1px solid var(--dsw-alias-border-l1,rgba(128,128,128,.4));border-radius:7px;padding:4px 10px;cursor:pointer;white-space:nowrap}",
  ".dc-btn:hover{background:var(--dsw-alias-interactive-bg-hover,rgba(128,128,128,.15))}",
  ".dc-btn:disabled{opacity:.4;cursor:default}",
  ".dc-btn-restore{border-color:var(--dsw-alias-state-ok-primary,rgba(80,160,120,.6))}",
  ".dc-btn-delete{color:var(--dsw-alias-state-error-primary,#d06c6c);border-color:var(--dsw-alias-state-error-primary,rgba(208,108,108,.5))}",
  ".dc-btn-danger{background:var(--dsw-alias-state-error-primary,#b5433f);border-color:transparent;color:var(--dsw-alias-label-primary-inverted,#fff)}",
  ".dc-error{color:var(--dsw-alias-state-error-primary,#e06c6c);font-size:12px;white-space:pre-wrap}",
  ".dc-loading{opacity:.6}"
].join("");
function insertCss() {
  if (typeof document === "undefined") return () => {
  };
  if (document.querySelector(`style[data-plugin-css="${CSS_TAG}"]`) !== null) return () => {
  };
  const style = document.createElement("style");
  style.dataset.plugin = PACKAGE;
  style.dataset.pluginCss = CSS_TAG;
  style.textContent = CSS;
  document.head.appendChild(style);
  return () => {
    if (style.parentNode !== null) style.parentNode.removeChild(style);
  };
}
async function call(remote, method, args) {
  const carried = await remote[method](...args ?? []);
  if (carried === null || typeof carried !== "object" || carried.ok !== true) {
    throw new Error(carried && carried.error && carried.error.message || `${method} \u8C03\u7528\u5931\u8D25`);
  }
  return carried.value;
}
function formatTime(ms) {
  try {
    return new Date(ms).toLocaleString();
  } catch {
    return String(ms);
  }
}
function SessionManagerPage(props) {
  const api = props.api;
  const [view, setView] = import_react.default.useState({
    loading: true,
    sessions: [],
    error: null,
    busyId: null,
    confirmId: null,
    confirmPath: null
  });
  const load = async () => {
    setView((s) => ({ ...s, loading: true }));
    try {
      const value = await call(api, "list", [{}]);
      setView({
        loading: false,
        sessions: value && value.sessions || [],
        error: null,
        busyId: null,
        confirmId: null,
        confirmPath: null
      });
    } catch (error) {
      setView({
        loading: false,
        sessions: [],
        error: String(error && error.message || error),
        busyId: null,
        confirmId: null,
        confirmPath: null
      });
    }
  };
  import_react.default.useEffect(() => {
    load();
  }, []);
  const toggleArchive = async (sessionId, archived2) => {
    setView((s) => ({ ...s, busyId: sessionId, error: null }));
    try {
      await call(api, archived2 ? "unarchive" : "archive", [{ sessionId }]);
      await load();
    } catch (error) {
      setView((s) => ({ ...s, busyId: null, error: String(error && error.message || error) }));
    }
  };
  const askDelete = async (sessionId) => {
    setView((s) => ({ ...s, busyId: sessionId, error: null, confirmPath: null }));
    try {
      const info = await call(api, "inspectDelete", [{ sessionId }]);
      if (info && info.deletable === true) {
        setView((s) => ({ ...s, busyId: null, confirmId: sessionId, confirmPath: info.path }));
      } else {
        setView((s) => ({
          ...s,
          busyId: null,
          confirmId: null,
          confirmPath: null,
          error: info && info.reason || "\u65E0\u6CD5\u5220\u9664"
        }));
      }
    } catch (error) {
      setView((s) => ({
        ...s,
        busyId: null,
        confirmId: null,
        confirmPath: null,
        error: String(error && error.message || error)
      }));
    }
  };
  const doDelete = async (sessionId) => {
    setView((s) => ({ ...s, busyId: sessionId, error: null }));
    try {
      await call(api, "deleteSession", [{ sessionId }]);
      await load();
    } catch (error) {
      setView((s) => ({
        ...s,
        busyId: null,
        confirmId: null,
        confirmPath: null,
        error: String(error && error.message || error)
      }));
    }
  };
  const renderRow = (session) => {
    const confirming = view.confirmId === session.id;
    const busy = view.busyId === session.id;
    return e(
      "div",
      { key: session.id, className: "dc-row" },
      e(
        "div",
        { className: "dc-row-main" },
        e("div", { className: "dc-row-title" }, session.title || "(\u672A\u547D\u540D\u4F1A\u8BDD)"),
        e(
          "div",
          { className: "dc-row-sub" },
          (session.cwd || "(\u65E0\u5DE5\u4F5C\u76EE\u5F55)") + " \xB7 " + formatTime(session.createdAt)
        ),
        session.live ? e("div", { className: "dc-live" }, "\u25CF \u8FD0\u884C\u4E2D\uFF08\u4E0D\u53EF\u5220\u9664\uFF09") : null,
        confirming ? e(
          "div",
          { className: "dc-warn" },
          "\u5C06\u6C38\u4E45\u5220\u9664\u8BE5\u4F1A\u8BDD\u65E5\u5FD7\u6587\u4EF6\uFF0C\u4E0D\u53EF\u64A4\u9500\uFF1A" + (view.confirmPath || "")
        ) : null
      ),
      e(
        "div",
        { className: "dc-actions" },
        e(
          "button",
          {
            className: "dc-btn" + (session.archived ? " dc-btn-restore" : ""),
            disabled: busy,
            onClick: () => toggleArchive(session.id, session.archived)
          },
          session.archived ? "\u53D6\u6D88\u5F52\u6863" : "\u5F52\u6863"
        ),
        confirming ? e(
          "button",
          { className: "dc-btn dc-btn-danger", disabled: busy, onClick: () => doDelete(session.id) },
          "\u786E\u8BA4\u5220\u9664"
        ) : e(
          "button",
          {
            className: "dc-btn dc-btn-delete",
            disabled: session.live || busy,
            onClick: () => askDelete(session.id)
          },
          "\u5220\u9664"
        ),
        confirming ? e(
          "button",
          {
            className: "dc-btn",
            onClick: () => setView((s) => ({ ...s, confirmId: null, confirmPath: null }))
          },
          "\u53D6\u6D88"
        ) : null
      )
    );
  };
  const renderSection = (title, sessions) => e(
    "div",
    { className: "dc-section" },
    e("div", { className: "dc-section-title" }, title + "\uFF08" + sessions.length + "\uFF09"),
    sessions.length === 0 ? e("div", { className: "dc-empty" }, "\u65E0") : sessions.map(renderRow)
  );
  const archived = view.sessions.filter((s) => s.archived);
  const active = view.sessions.filter((s) => !s.archived);
  return e(
    "div",
    { className: "dc-root" },
    e(
      "div",
      { className: "dc-head" },
      e("div", { className: "dc-head-title" }, "\u4F1A\u8BDD\u7BA1\u7406"),
      e("button", { className: "dc-btn", onClick: load }, "\u5237\u65B0")
    ),
    view.error ? e("div", { className: "dc-error" }, "\u9519\u8BEF\uFF1A" + view.error) : null,
    view.loading ? e("div", { className: "dc-loading" }, "\u52A0\u8F7D\u4E2D\u2026") : e("div", null, renderSection("\u5DF2\u5F52\u6863\uFF08\u53EF\u6062\u590D\u663E\u793A\uFF09", archived), renderSection("\u6B63\u5E38\u4F1A\u8BDD", active))
  );
}
async function apply(ctx) {
  const remote = ctx.remote;
  if (remote === void 0 || typeof remote.$mount !== "function") return;
  const unmount = await remote.$mount(REMOTE_CONTRIBUTION);
  ctx.effect(() => () => {
    unmount();
  }, "del-chat: remote contribution");
  const api = ctx.get("remote." + NAMESPACE);
  if (api === void 0) return;
  const removeCss = insertCss();
  ctx.effect(() => () => removeCss(), "del-chat: stylesheet");
  const slots = ctx.get("slots");
  if (slots === void 0) return;
  slots.inject(
    "settings.section",
    () => slots.register(
      { name: "settings.section", id: SECTION_ID, order: 50, label: "\u4F1A\u8BDD\u7BA1\u7406" },
      (props) => e(SessionManagerPage, { ...props, api })
    )
  );
}

    })(module, exports, require);
    return module.exports;
  },
});
