// Generated by scripts/build.mjs — do not edit directly.

// src/index.js
var name = "del-chat";
function archivedIdsOf(registry) {
  if (registry === void 0) return [];
  try {
    return registry.archivedSessionIds.map((id) => String(id));
  } catch {
    return [];
  }
}
function parentDir(p) {
  const i = Math.max(p.lastIndexOf("\\"), p.lastIndexOf("/"));
  return i > 0 ? p.slice(0, i) : p;
}
function titleFromValue(value) {
  if (typeof value === "string" && value.length > 0) return value;
  if (value !== null && typeof value === "object" && typeof value.title === "string" && value.title.length > 0) {
    return value.title;
  }
  return null;
}
function resolveTitle(ctx, header, liveSession) {
  if (liveSession !== void 0) {
    const projections = ctx.get("sessionProjections");
    if (projections !== void 0) {
      try {
        const title = titleFromValue(projections.snapshot(liveSession)?.values?.title);
        if (title !== null) return title;
      } catch {
      }
    }
    const sessionTitle = ctx.get("sessionTitle");
    if (sessionTitle !== void 0) {
      try {
        const title = titleFromValue(sessionTitle.get(liveSession));
        if (title !== null) return title;
      } catch {
      }
    }
    return null;
  }
  const cache = ctx.get("sessionProjectionCache");
  if (cache !== void 0) {
    try {
      return titleFromValue(cache.cachedSnapshot(header)?.values?.title);
    } catch {
    }
  }
  return null;
}
async function inspectDeletable(ctx, sessionId) {
  const sessions = ctx.get("sessions");
  if (sessions !== void 0 && sessions.get(sessionId) !== void 0) {
    return { deletable: false, reason: "\u8BE5\u4F1A\u8BDD\u6B63\u5728\u8FD0\u884C\uFF0C\u65E0\u6CD5\u5220\u9664", path: null, dir: null };
  }
  const persistence = ctx.get("sessionPersistence");
  if (persistence === void 0) {
    return { deletable: false, reason: "\u5B58\u50A8\u670D\u52A1\u4E0D\u53EF\u7528", path: null, dir: null };
  }
  let header;
  try {
    const list = await persistence.list();
    header = list.find((h) => String(h.id) === sessionId);
  } catch {
    header = void 0;
  }
  if (header === void 0) {
    return { deletable: false, reason: "\u4F1A\u8BDD\u4E0D\u5B58\u5728", path: null, dir: null };
  }
  if (persistence.supportsRawArtifacts !== true) {
    return { deletable: false, reason: "\u5F53\u524D\u5B58\u50A8\u540E\u7AEF\u4E0D\u66B4\u9732\u5355\u4F1A\u8BDD\u6587\u4EF6\uFF0C\u65E0\u6CD5\u5B89\u5168\u5220\u9664", path: null, dir: null };
  }
  const loc = persistence.locate(header);
  if (loc === void 0 || loc.kind !== "jsonl") {
    return { deletable: false, reason: "\u65E0\u6CD5\u89E3\u6790\u4F1A\u8BDD\u6587\u4EF6\u8DEF\u5F84", path: null, dir: null };
  }
  const base = String(loc.path).split(/[\\/]/).pop() ?? "";
  if (!base.startsWith("session.jsonl")) {
    return { deletable: false, reason: "\u4EA7\u7269\u6587\u4EF6\u540D\u5F02\u5E38\uFF0C\u5DF2\u62D2\u7EDD\u5220\u9664", path: null, dir: null };
  }
  return { deletable: true, reason: null, path: String(loc.path), dir: parentDir(String(loc.path)) };
}
function createService(ctx) {
  const service = {
    /** Every session, newest first inside each archive group. */
    async list() {
      const query = ctx.get("sessionQuery");
      const registry = ctx.get("workspaceRegistry");
      const sessions = ctx.get("sessions");
      const archivedIds = archivedIdsOf(registry);
      const archivedSet = new Set(archivedIds);
      if (query === void 0) return { sessions: [] };
      const records = await query.listSessions();
      const liveSet = /* @__PURE__ */ new Set();
      const liveById = /* @__PURE__ */ new Map();
      if (sessions !== void 0) {
        for (const s of sessions.list()) {
          liveSet.add(String(s.id));
          liveById.set(String(s.id), s);
        }
      }
      const out = records.map((r) => {
        const id = String(r.header.id);
        const cwd = r.header.cwd;
        return {
          id,
          title: resolveTitle(ctx, r.header, liveById.get(id)),
          cwd: typeof cwd === "string" && cwd.length > 0 ? cwd : null,
          createdAt: Number(r.header.createdAt) || 0,
          live: liveSet.has(id) || r.live === true,
          archived: archivedSet.has(id)
        };
      });
      out.sort((a, b) => a.archived === b.archived ? b.createdAt - a.createdAt : a.archived ? -1 : 1);
      return { sessions: out };
    },
    /** Archive (hide) one session durably. */
    async archive(request) {
      const registry = ctx.get("workspaceRegistry");
      if (registry === void 0) throw new Error("workspace registry unavailable");
      await registry.archiveSession(String(request.sessionId));
      return { archivedSessionIds: archivedIdsOf(registry) };
    },
    /**
     * Unarchive (restore) one session by removing it from the registry-global
     * archive set. Goes through the registry's own state setter so its
     * in-memory cache stays consistent with the durable domain.
     */
    async unarchive(request) {
      const registry = ctx.get("workspaceRegistry");
      const storageDomain = ctx.get("storageDomain");
      if (registry === void 0 || storageDomain === void 0) {
        throw new Error("workspace registry unavailable");
      }
      const domain = storageDomain.get("workspace");
      if (domain === void 0) throw new Error("workspace domain unavailable");
      const state = domain.global.get();
      const archived = state.archivedSessionIds ?? [];
      const next = archived.filter((id) => String(id) !== String(request.sessionId));
      if (next.length === archived.length) {
        return { archivedSessionIds: archived.map((id) => String(id)) };
      }
      const nextState = { ...state, archivedSessionIds: next };
      if (typeof registry.setState === "function") {
        await registry.setState(nextState);
      } else {
        await domain.global.set(nextState);
        registry.state = nextState;
      }
      return { archivedSessionIds: next.map((id) => String(id)) };
    },
    /** Whether one session's log file can be deleted, and where it is. */
    async inspectDelete(request) {
      return await inspectDeletable(ctx, String(request.sessionId));
    },
    /**
     * Permanently delete one non-live session's persistence log file, then
     * detach it from workspace accounting and from the archive set.
     */
    async deleteSession(request) {
      const sessionId = String(request.sessionId);
      const info = await inspectDeletable(ctx, sessionId);
      if (!info.deletable) throw new Error(info.reason ?? "session is not deletable");
      const shell = ctx.get("shell");
      if (shell === void 0) throw new Error("shell service unavailable");
      const quoted = info.path.replace(/'/g, "''");
      const spec = shell.resolve({ command: `Remove-Item -LiteralPath '${quoted}' -Force -ErrorAction Stop` });
      const result = await shell.run(spec);
      if (result.sandbox && result.sandbox.denied) {
        throw new Error("\u6C99\u7BB1\u62D2\u7EDD\u4E86\u5220\u9664\uFF08\u4F1A\u8BDD\u6587\u4EF6\u4F4D\u4E8E\u5DE5\u4F5C\u533A\u4E4B\u5916\uFF09");
      }
      if (result.exitCode !== 0) {
        throw new Error(`\u5220\u9664\u547D\u4EE4\u5931\u8D25\uFF08exit ${result.exitCode}\uFF09`);
      }
      try {
        await service.unarchive({ sessionId });
      } catch {
      }
      const registry = ctx.get("workspaceRegistry");
      if (registry !== void 0) {
        try {
          for (const workspace of registry.list()) {
            await workspace.detachSession(sessionId);
          }
        } catch {
        }
      }
      return { path: info.path };
    }
  };
  Object.defineProperty(service, "typertRemote", {
    configurable: false,
    enumerable: false,
    writable: false,
    value: { service, serviceKey: "delChat", namespace: "delChat" }
  });
  return service;
}
function apply(ctx) {
  ctx.provide("delChat", createService(ctx));
}
export {
  apply,
  name
};
