/**
 * Build dsh-del-chat into its published `lib/` artifacts.
 *
 *   lib/index.js        host plugin (ESM, bundled, zod-free)
 *   lib/typert.host.js  hand-written Host-face Typert manifest (copied verbatim)
 *   lib/client.js       browser bundle in the `window.__ModuleLoader__.load({...})`
 *                       envelope the DSH client module system executes, with
 *                       `react` left external for the shell's static table
 *
 * Run with: node scripts/build.mjs
 */
import { build } from 'esbuild'
import { copyFile, mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const outDir = join(root, 'lib')
const pkg = JSON.parse(await readFile(join(root, 'package.json'), 'utf8'))

await mkdir(outDir, { recursive: true })

const banner = '// Generated by scripts/build.mjs — do not edit directly.'

// ── host half ────────────────────────────────────────────────────────────────
await build({
  entryPoints: [join(root, 'src/index.js')],
  outfile: join(outDir, 'index.js'),
  bundle: true,
  format: 'esm',
  platform: 'node',
  target: 'node20',
  banner: { js: banner },
  logLevel: 'info',
})

// ── host-face Typert manifest (hand-written source, copied as-is) ─────────────
await copyFile(join(root, 'src/typert.host.js'), join(outDir, 'typert.host.js'))

// ── browser half ─────────────────────────────────────────────────────────────
const client = await build({
  entryPoints: [join(root, 'src/client.js')],
  bundle: true,
  write: false,
  format: 'cjs',
  platform: 'browser',
  target: 'es2022',
  // Resolved from the shell's static module table at run time, never bundled.
  external: ['react', 'react-dom', 'react/jsx-runtime'],
  define: { 'process.env.NODE_ENV': '"production"' },
  logLevel: 'info',
})

const bundled = client.outputFiles[0].text

const envelope = `${banner}
window.__ModuleLoader__.load({
  id: ${JSON.stringify(pkg.name)},
  factory: function (require) {
    var module = { exports: {} };
    var exports = module.exports;
    (function (module, exports, require) {
${bundled}
    })(module, exports, require);
    return module.exports;
  },
});
`

await writeFile(join(outDir, 'client.js'), envelope, 'utf8')

console.log(`[dsh-del-chat] built lib/index.js, lib/typert.host.js, lib/client.js`)
